# Generated by Django 4.0.5 on 2022-08-09 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_instalaciones_nosotros_perfil_socios_delete_curso_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
