# Generated by Django 4.0.5 on 2022-08-10 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_delete_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socios',
            name='numeroDeSocio',
        ),
    ]
